### ISSUE TITLE
Spatial Index Commit Failure ved oprettelse af nyt fikspunkt

### ISSUE THREAD

**Issue by ReneTandsbjerg** [SDFIdk/FIRE#672]
[2022_10KM_BLOK.xlsx](https://github.com/SDFIdk/FIRE/files/10678738/2022_10KM_BLOK.xlsx)

```
(base) C:\>f:

(base) F:\>mamba activate fire

(fire) F:\>cd F:\GRF\Data\GEO\BC\Niv_Opgaver\2022\10KM_BLOK

(fire) F:\GRF\Data\GEO\BC\Niv_Opgaver\2022\10KM_BLOK>fire niv ilæg-nye-punkter 2022_10KM_BLOK
Sags/projekt-navn: 2022_10KM_BLOK  (2397b9a5-df38-4a1d-ae62-4c93fa13650a)
Sagsbehandler:     b012858
Behandler punkter
Behandler punktinformationer
Du indsætter nu 1 punkter i prod-databasen - er du sikker? (ja/NEJ):
ja
Gentag svar for at bekræfte (ja/NEJ)
ja
Traceback (most recent call last):
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\base.py", line 1089, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\default.py", line 686, in do_commit
    dbapi_connection.commit()
cx_Oracle.DatabaseError: ORA-13199: Spatial Index Commit Failure

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\Scripts\fire-script.py", line 33, in <module>
    sys.exit(load_entry_point('fire', 'console_scripts', 'fire')())
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\fire\fire\cli\niv\_ilæg_nye_punkter.py", line 338, in ilæg_nye_punkter
    fire.cli.firedb.session.commit()
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\orm\session.py", line 836, in commit
    trans.commit()
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\base.py", line 2459, in commit
    self._do_commit()
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\base.py", line 2649, in _do_commit
    self._connection_commit_impl()
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\base.py", line 2620, in _connection_commit_impl
    self.connection._commit_impl()
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\base.py", line 1091, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\base.py", line 1089, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "C:\Users\b012858\AppData\Local\mambaforge\envs\fire\lib\site-packages\sqlalchemy\engine\default.py", line 686, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-13199: Spatial Index Commit Failure
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```
@xidus

**Comment by kbevers** [comment]
Jeg tror det må have været en midlertidig fejl på databasen. Jeg har i hvert fald lige kørt `fire niv ilæg-nye-punkter` med succes:
```
(fire-1.5) C:\Temp\fire\ReneSpatialIndex>fire niv ilæg-nye-punkter --db prod 2022_10KM_BLOK  
Sags/projekt-navn: 2022_10KM_BLOK  (2397b9a5-df38-4a1d-ae62-4c93fa13650a)
Sagsbehandler:     B012349
Behandler punkter
Behandler punktinformationer
Du indsætter nu 1 punkter i prod-databasen - er du sikker? (ja/NEJ):
ja
Gentag svar for at bekræfte (ja/NEJ)
ja
Skriver: {'Sagsgang', 'Nyetablerede punkter'}
Til filen '2022_10KM_BLOK.xlsx'
Overskriver fanebladene {'Sagsgang', 'Nyetablerede punkter'}
    med opdaterede versioner.
Foregående versioner beholdes i 'ex'-filen '2022_10KM_BLOK-ex.xlsx'
Punkter oprettet. Resultater skrevet til '2022_10KM_BLOK.xlsx'

(fire-1.5) C:\Temp\fire\ReneSpatialIndex>start 2022_10KM_BLOK.xlsx
```

Du får lige en kopi af de to regneark der hører til sagen:

[2022_10KM_BLOK.xlsx](https://github.com/SDFIdk/FIRE/files/10685368/2022_10KM_BLOK.xlsx)
[2022_10KM_BLOK-ex.xlsx](https://github.com/SDFIdk/FIRE/files/10685369/2022_10KM_BLOK-ex.xlsx)

Det nye punkter hedder `58-05-09030`: 

```
>fire info punkt --db prod 58-09-09072

--------------------------------------------------------------------------------
 PUNKT 58-09-09072
--------------------------------------------------------------------------------
  Lokation                    POINT (9.57964247 57.17991977)
  Oprettelsesdato             2023-01-19 21:35:52.845964
  AFM:højde_over_terræn       -0.5
  AFM:2701                    Lodret bolt
  ATTR:beskrivelse            Halvrimmenvej V. side.
                              Underføring.
                              Punkt i betonrør, midte.
                              0,10 m fra S. ende.
  REGION:DK
  ATTR:bemærkning             Nyetb. 2023 B152590
  ATTR:højdefikspunkt
  IDENT:landsnr               58-09-09072

--- KOORDINATER ---
```
